basedir = "data/"
safe_window = 10
proposal_window = 10

# If we wanna generate inifite transactions so that bench can run infinitely,
# we can let the `miner` and `alice` be the same acount and miner mines new
# block reward to provide `alice` run benchmarks.
#
# NOTE: We should ensure the ckb-miner is same as we configurated here.
bank  = "<miner-private-key>"
alice = "<miner-private-key>"

# The rpc urls of ckb node
rpc_urls = [ "http://127.0.0.1:8114/" ]

[logger]
filter = "info,ckb-bench=debug"
file = "data/logs/bench.log"
color = true
log_to_file = true
log_to_stdout = true

[[miners]]
rpc_url = "http://127.0.0.1:8114"
delay_type = { Uniform = { low = 1000, high = 2000 } }

# When bench the sending-transaction-rate, keep `adjust_origin`
# and `adjust_step` as `0`.
[serial]
conditions = "{\"In2Out2\":1,\"RandomFee\":1}"
transactions = 4000
adjust_cycle = 100
adjust_origin= { secs = 0, nanos = 0 }
adjust_step = { secs = 0, nanos = 0 }
adjust_misbehavior = 5000000
