basedir = "data/"
safe_window = 10
proposal_window = 10

bank = "<bank private key>"
alice = "<alice private key>"

rpc_urls = [ "http://127.0.0.1:8114/" ]

[logger]
filter = "info,ckb-bench=debug"
color = true
file = "data/logs/bench.log"
log_to_file = true
log_to_stdout = true

[[miners]]
rpc_url = "http://127.0.0.1:8114"
delay_type = { Uniform = { low = 1000, high = 2000 } }

[serial]
conditions = "{\"In2Out2\":1,\"RandomFee\":1}"
transactions = 1000
adjust_cycle = 100
adjust_origin= { secs = 0, nanos = 5_000_000 } # 5ms
adjust_step = { secs = 0, nanos = 100_000 }   # 0.1ms
adjust_misbehavior = 50
