---
- hosts: all
  name: Setup common packages
  user: ubuntu
  roles:
    - role: common
      vars:
        rust_version: 1.34.2

- hosts: bastion
  name: Setup bastion
  user: ubuntu
  roles:
    - role: bastion
      vars:
        checkouts: /home/ubuntu/checkouts
        # can use branch / tag / commit hash here
        ckb_version: develop
        netdata_api_key: c2028a92-d68c-4595-a5ad-1e53e5e0c27d
        netdata_bind_ip: 0.0.0.0

- hosts: instances[0]
  name: Setup bootnode
  user: ubuntu
  roles:
    - role: bootnode
      vars:
        run_folder: /var/lib/ckb

- hosts: instances
  strategy: free
  name: Setup ckb bench instances
  user: ubuntu
  roles:
    - role: instances
      vars:
        checkouts: /home/ubuntu/checkouts
        run_folder: /var/lib/ckb
        ckb_version: develop
        netdata_api_key: c2028a92-d68c-4595-a5ad-1e53e5e0c27d
        netdata_bind_ip: 0.0.0.0
        netdata_master_ip: 10.0.1.100
        netdata_influxdb: "tcp:10.0.1.100:4242"
