---
- hosts: all
  name: Setup common packages
  user: ubuntu
  roles:
    - role: common
      vars:
        rust_version: 1.34.2

- hosts: bootnode
  name: Setup bootnode
  user: ubuntu
  roles:
    - role: bootnode
      vars:
        run_folder: /var/lib/ckb

- hosts: all
  name: Setup ckb service
  user: ubuntu
  roles:
    - role: ckb_service
      vars:
        checkouts: /home/ubuntu/checkouts
        run_folder: /var/lib/ckb
        ckb_version: 4f46d847986b9bea15f5ec4b18b0de9083568a99
